/*
 * color.legacy.lut_collection — "LUT Collection 1"
 *
 * v2 port of the shipped Resolume Wire "LUT 2" patch: a stripped-down LUT
 * grader that applies one of a set of baked preset colour LUTs with a pregain
 * curve and a mix amount. The original applied each preset through the ISF
 * `LUTShader`, hand-addressing a 64^3 cube packed into a 512x512 8x8 strip
 * (two taps + a manual trilinear blend per pixel).
 *
 * The team asked us to "implement more efficiently" and were happy to keep the
 * baked static LUT resources. So this port:
 *   - bakes the 13 preset strips into real 64^3 rgba8 3D textures ONCE
 *     (lut_data.h, generated by gen_lut_data.py — replicates the exact ISF
 *     strip addressing so the cube is a faithful copy of the source), then
 *   - does the lookup in a SINGLE hardware-trilinear 3D sample per pixel.
 *
 * The cube is baked at the source strips' native 64^3 (a direct copy, no
 * resampling). An earlier 32^3 downsample showed visible blockiness in dark
 * regions — the linear-indexed axis under-samples shadows, where the eye is
 * most sensitive — so we keep full resolution for parity with the original.
 *
 * Pipeline:
 *   bake (once):  fill.hlsl copies each preset's bytes (staging storage buffer)
 *                 into its 3D texture.
 *   render:       apply.hlsl — coord = pow(in, power); graded = pow(LUT(coord),
 *                 1/power); out = lerp(in, graded, amount). Keeps input alpha.
 *
 * Pregain -> power follows the patch's node math: Pregain*5, then a piecewise
 * reciprocal exponent (see pregain_to_power). Pregain 0 => power 1 (neutral).
 *
 * Class-like instance ABI: module_init() compiles the two shared PSOs +
 * sampler and publishes the schema once per type; the 13 LUT textures are
 * type-shared (immutable after bake) file statics baked lazily on first render.
 * Per-instance State holds only the params + the apply uniform buffer.
 */

#include <gpu.h>
#include <host.h>
#include "lut_collection_shaders.h"
#include "lut_data.h"

namespace lut_collection {

struct ApplyUniforms {
  float amount;
  float power;
  float invPower;
  float _pad;
};

// Per-instance state. One per chain entry.
struct State {
  int   lut = 0;
  float amount = 1.0f;    // ISF "Alpha" mix (full LUT by default, like the patch)
  float pregain = 0.0f;   // [-1,1] -> power curve
  bool  initialized = false;
  gpu::Buffer uniform_buf;
};

// Type-shared: compiled once in module_init().
static gpu::ComputePSO s_pso_fill;
static gpu::ComputePSO s_pso_apply;
static gpu::Sampler    s_samp;

// Type-shared LUT cubes, baked once (immutable after). On the native barrel
// these are shared across all instances; on web each module instance has its
// own statics — either way the bake is idempotent.
static gpu::Texture s_luts[LUT_COUNT];
static bool s_baked = false;

// Pregain in [-1,1] -> power exponent, matching the LUT 2 patch:
//   p>=0:  1/(1+5p)   in (0,1]  (push toward highlights before lookup)
//   p<0:   1-5p       in [1,6]  (push toward shadows)
// C1 at p=0 (both give 1, slope -5); reciprocal-symmetric at the extremes.
static inline float pregain_to_power(float p) {
  float m = p * 5.0f;
  float power = (p >= 0.0f) ? (1.0f / (1.0f + m)) : (1.0f - m);
  if (power < 1e-3f) power = 1e-3f;
  return power;
}

void module_init() {
  state::init("color.legacy.lut_collection", {1, 0, 0},
    state::Schema()
      .selectField("lut", 0, state::PrimaryInput, {
        {"Process", 0}, {"Instant", 1}, {"Fade", 2}, {"Chrome", 3},
        {"Transfer", 4}, {"Tonal", 5}, {"Mono", 6}, {"Noir", 7},
        {"Saturation + Contrast", 8}, {"Saturation/Contrast (More)", 9},
        {"Hue Rotate 90", 10}, {"Hue Rotate 180", 11}, {"Hue Rotate 270", 12},
      }, /*wrap=*/true, "Which baked preset LUT to apply.")
      .floatField("amount", 1.0f, 0.0f, 1.0f, state::PrimaryInput, nullptr, 0.0f, nullptr,
                  "Mix between the input and the graded result.")
      .floatField("pregain", 0.0f, -1.0f, 1.0f, state::PrimaryInput, nullptr, 0.0f, nullptr,
                  "Tone push into the LUT: + toward highlights, - toward shadows.")
      .textureField("tex_in",  state::PrimaryInput)
      .textureField("tex_out", state::PrimaryOutput)
      .capability(state::Capability::TimeIndependent));

  if (gpu::Device::backend() == gpu::Backend::None) return;

  // Fill writes the semantic-8-bit 3D cube: pinned rgba8unorm for the naga
  // bridge. Apply writes tex_out and follows the sketch-default format.
  state::registerShaderSPV("lut_collection_fill",  FILL_SPV,  FILL_SPV_SIZE,  "rgba8unorm", "write");
  state::registerShaderSPV("lut_collection_apply", APPLY_SPV, APPLY_SPV_SIZE);

  auto cs_fill  = gpu::Device::createShaderModuleByName("lut_collection_fill");
  auto cs_apply = gpu::Device::createShaderModuleByName("lut_collection_apply");
  if (!cs_fill || !cs_apply) return;

  s_pso_fill = gpu::Device::createComputePSO(cs_fill, "main", gpu::Bindings()
      .storageTex3d(0, gpu::TextureFormat::RGBA8)
      .storage(1));
  s_pso_apply = gpu::Device::createComputePSO(cs_apply, "main", gpu::Bindings()
      .tex2d(0)
      .tex3d(1)
      .sampler(2)
      .storageTex2d(3)
      .uniform(4));

  s_samp = gpu::Device::createSampler(gpu::FilterMode::Linear, gpu::AddressMode::ClampToEdge);

  state::log("lut_collection: module initialized");
}

void* create() {
  auto* s = new State();
  s->uniform_buf = gpu::Device::createBuffer(sizeof(ApplyUniforms), gpu::BufferUsage::Uniform);
  return s;
}

void destroy(void* self) {
  auto* s = static_cast<State*>(self);
  if (!s) return;
  s->uniform_buf.release();
  delete s;
}

void init(void* self) {
  auto* s = static_cast<State*>(self);
  if (!s || !s->uniform_buf.valid()) return;
  if (!s_pso_fill.valid() || !s_pso_apply.valid()) return;
  s->initialized = true;
}

void tick(void* self, double) {
  (void)self;
}

void on_state_patched(void* self, int n, const char* pb, const int* off,
                      const int* len, const int* ops) {
  auto* s = static_cast<State*>(self);
  if (!s) return;
  for (int i = 0; i < n; i++) {
    if (ops[i] != state::PatchReplace) continue;
    const char* p = pb + off[i];
    int l = len[i];
    if (state::pathIs(p, l, "lut"))     s->lut = state::patchInt(i);
    if (state::pathIs(p, l, "amount"))  s->amount = state::patchFloat(i);
    if (state::pathIs(p, l, "pregain")) s->pregain = state::patchFloat(i);
  }
}

// amount==0 -> output is exactly the input (lerp(c, graded, 0) = c, alpha kept).
// Stateless: safe to skip the dispatch entirely.
int32_t is_identity(void* self) {
  auto* s = static_cast<State*>(self);
  return (s && s->amount <= 0.0f) ? 1 : 0;
}

// One-time bake: upload each preset's bytes and fill its 3D cube. Type-shared;
// runs on the first render only.
//
// One staging buffer PER preset — never reuse one buffer across dispatches in
// a frame. `writeBytes` is an immediate CPU write while the native executor
// defers every effect-called submit() into one whole-frame command buffer, so
// a write→dispatch→write loop on a shared buffer has every dispatch read the
// LAST write (all 13 cubes ended up holding "Hue Rotate 270").
static void bake() {
  gpu::Buffer stages[LUT_COUNT];
  for (int i = 0; i < LUT_COUNT; i++) {
    s_luts[i] = gpu::Device::createTexture3D(LUT_DIM, LUT_DIM, LUT_DIM, gpu::TextureFormat::RGBA8);
    stages[i] = gpu::Device::createBuffer(LUT_BYTES, gpu::BufferUsage::Storage);
    stages[i].writeBytes(&LUT_DATA[i * LUT_BYTES], LUT_BYTES);
    auto cp = gpu::ComputePass::begin();
    cp.setPSO(s_pso_fill);
    cp.setTexture(s_luts[i], 0, 1);   // storage write (3D)
    cp.setBuffer(stages[i], 1);
    cp.dispatch((LUT_DIM + 3) / 4, (LUT_DIM + 3) / 4, (LUT_DIM + 3) / 4);
    cp.end();
  }
  // Flush the fills before releasing the staging (web: a real queue submit;
  // native: no-op — the frame batch retains encoded resources past release).
  gpu::Device::submit();
  for (int i = 0; i < LUT_COUNT; i++) stages[i].release();
  s_baked = true;
}

void render(void* self, int w, int h) {
  auto* s = static_cast<State*>(self);
  if (!s || !s->initialized || w <= 0 || h <= 0) return;
  auto in  = gpu::Device::textureForField("tex_in");
  auto out = gpu::Device::textureForField("tex_out");
  if (!in.valid() || !out.valid()) return;

  if (!s_baked) bake();

  int idx = s->lut;
  if (idx < 0) idx = 0;
  if (idx >= LUT_COUNT) idx = LUT_COUNT - 1;
  if (!s_luts[idx].valid()) return;

  float power = pregain_to_power(s->pregain);
  ApplyUniforms u = { s->amount, power, 1.0f / power, 0.0f };
  s->uniform_buf.writeOne(u);

  auto cp = gpu::ComputePass::begin();
  cp.setPSO(s_pso_apply);
  cp.setTexture(in,         0, 0);
  cp.setTexture(s_luts[idx], 1, 0);  // sampled 3D LUT
  cp.setSampler(s_samp,     2);
  cp.setTexture(out,        3, 1);   // storage write 2D
  cp.setBuffer(s->uniform_buf, 4);
  cp.dispatch((w + 7) / 8, (h + 7) / 8);
  cp.end();
  gpu::Device::submit();
}

} // namespace lut_collection
