"""Generate shape_fold_atlas.h from the shape-fold research atlas.json.

The atlas is the baked 3D control surface (frequency × simplicity × temporal-
complexity) of resolved shape parameters. shape_fold's CPU `sampleTerms` reads
it directly (it never touches the GPU), so we embed it as a committed C++ header
of flat float arrays — mirroring research/shape-fold/web/build_data.py's layout:

  base term fields  [G,G,B]    row-major (gi*G+gj)*B + ti     (shared across z)
  cell fields       [G,G]      row-major gi*G+gj
  script fields     [G,G,Z,B]  row-major ((gi*G+gj)*Z+z)*B + ti

Run once and commit the output (no build-time python dependency):

    python3 native/wasm_modules/shape_fold/gen_atlas.py \
        [--atlas /path/to/shapes/research/shape-fold/web/atlas.json]
"""

import argparse
import json
import os

BASE_TERM_FIELDS = ["theta", "mtheta", "curv", "freq", "phase", "h", "k", "amp", "mix", "spc"]
CELL_FIELDS = ["dc", "bold_gain"]
SCRIPT_FIELDS = ["amp_h", "omega_h", "psi_h", "drift"]
# Key-moment sidecar (per (cell,z), row-major (gi*G+gj)*Z+z; FRAME INDICES into a
# km_nframes loop). Baked by the prototype's web/build_data.py via km.scan_atlas.
# The runtime uses only km_peak (playback anchor) + km_score (>0 ⇒ has a window);
# km_onset/km_len are the analyzed inflow span, kept for completeness/debug.
KM_FIELDS = ["km_onset", "km_len", "km_peak", "km_score"]
HERE = os.path.dirname(os.path.abspath(__file__))
# The shape-fold research prototype (nano-fx-prototypes) is the atlas source; its
# web/atlas.json carries the baked km_* sidecar arrays alongside the shape params.
DEFAULT_ATLAS = os.path.join(
    HERE, "..", "..", "..", "..", "nano-fx-prototypes", "shape-fold", "web", "atlas.json")


def fmt(v):
    # Compact float literal: drop trailing zeros, keep enough precision. Ensure a
    # decimal point/exponent so the `f` suffix is valid C++ ("1" -> "1.0", not "1f").
    s = f"{float(v):.5g}"
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s


def emit_array(fh, name, values):
    fh.write(f"static const float {name}[{len(values)}] = {{\n")
    line = "  "
    for v in values:
        tok = fmt(v) + "f,"
        if len(line) + len(tok) > 100:
            fh.write(line + "\n")
            line = "  "
        line += tok
    if line.strip():
        fh.write(line + "\n")
    fh.write("};\n\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--atlas", default=DEFAULT_ATLAS)
    args = ap.parse_args()

    with open(args.atlas) as f:
        atlas = json.load(f)

    G = int(atlas["grid"])
    B = int(atlas["n_terms"])
    Z = int(atlas["n_z"])
    tc = [float(v) for v in atlas["tc_centers"]]

    out_path = os.path.join(HERE, "shape_fold_atlas.h")
    with open(out_path, "w") as fh:
        fh.write("// AUTO-GENERATED by gen_atlas.py from the shape-fold research atlas. Do not edit.\n")
        fh.write("// Baked 3D shape-parameter atlas: frequency (x) x simplicity (y) x\n")
        fh.write("// temporal-complexity (z). CPU-only data — sampleTerms reads it directly.\n")
        fh.write("#ifndef SHAPE_FOLD_ATLAS_H\n#define SHAPE_FOLD_ATLAS_H\n\n")
        fh.write("namespace shape_fold {\n\n")
        fh.write(f"static const int   SF_GRID    = {G};\n")
        fh.write(f"static const int   SF_NTERMS  = {B};\n")
        fh.write(f"static const int   SF_NZ      = {Z};\n")
        fh.write(f"static const float SF_TC_CENTERS[{Z}] = {{ {', '.join(fmt(v) + 'f' for v in tc)} }};\n\n")
        for name in BASE_TERM_FIELDS + CELL_FIELDS + SCRIPT_FIELDS:
            emit_array(fh, "SF_" + name.upper(), atlas[name])
        # Key-moment sidecar. Degenerate to all-zero windows (km_score 0 ⇒ every
        # cell falls back to the full loop) when the atlas predates the km bake.
        n = G * G * Z
        km_nframes = int(atlas.get("km_nframes", 0))
        nvalid = sum(1 for v in atlas.get("km_score", []) if v > 0)
        fh.write(f"static const int   SF_KM_NFRAMES = {km_nframes};\n\n")
        for name in KM_FIELDS:
            emit_array(fh, "SF_" + name.upper(), atlas.get(name, [0.0] * n))
        fh.write("} // namespace shape_fold\n\n")
        fh.write("#endif // SHAPE_FOLD_ATLAS_H\n")

    print(f"wrote {out_path} ({G}x{G}x{Z}, {B} terms, tc_centers={tc}; "
          f"key moments {nvalid}/{n} cells over {km_nframes} frames)")


if __name__ == "__main__":
    main()
