#!/usr/bin/env python3
"""Bake the phase-fold research atlas.json into phase_fold_atlas.h.

The atlas is a GxG grid of emergent level-set limit-cycle FIELDS. Each cell
stores the scalar field's parameters (well/level/mu + K blob kernels + R ring
ridges), a per-cell WIND vector (the non-potential z-axis force) and a SEED
point on the resting cycle (curve layer 0, point 0) used to start the limit-
cycle tracer.

Unlike shape_fold (whose atlas is CPU-only and resolved to a few uniform
"terms"), phase_fold needs the raw cell parameters on the GPU: the backdrop
evaluates the blended field per-pixel and the streamline / limit-cycle tracers
integrate the blended vector field on the GPU. So we pack every cell into a
flat, GPU-uploadable PF_CELLS[] buffer with stride PF_STRIDE, matching the
WGSL layout in common.hlsl exactly.

Cell layout (PF_STRIDE = 4 + K*4 + R*3 + 5 floats):
  [0] well   [1] level   [2] mu   [3] valid
  [4 + k*4 + 0..3]            K blob kernels: cx, cy, sigma, w
  [4 + K*4 + j*3 + 0..2]      R ring ridges: r_rad, r_sig, r_amp
  [4 + K*4 + R*3 + 0]         wdx   (wind direction x)
  [4 + K*4 + R*3 + 1]         wdy   (wind direction y)
  [4 + K*4 + R*3 + 2]         wmax  (wind magnitude at z=1)
  [4 + K*4 + R*3 + 3]         seed_x
  [4 + K*4 + R*3 + 4]         seed_y
"""

import argparse
import json
import os


def fmt_float(v):
    v = float(v)
    if v != v or v in (float("inf"), float("-inf")):
        v = 0.0
    s = f"{v:.6g}"
    # Ensure a valid C float literal: must contain '.', 'e' or 'E' before 'f'.
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def emit_float_array(fh, name, values):
    fh.write(f"static const float {name}[{len(values)}] = {{\n")
    line = "  "
    for v in values:
        tok = fmt_float(v) + ","
        if len(line) + len(tok) > 100:
            fh.write(line + "\n")
            line = "  "
        line += tok
    if line.strip():
        fh.write(line + "\n")
    fh.write("};\n\n")


def main():
    ap = argparse.ArgumentParser()
    here = os.path.dirname(os.path.abspath(__file__))
    ap.add_argument(
        "--atlas",
        default=os.path.join(
            here, "..", "..", "..", "..", "shapes", "research",
            "phase-fold", "web", "atlas.json",
        ),
    )
    ap.add_argument("--out", default=os.path.join(here, "phase_fold_atlas.h"))
    args = ap.parse_args()

    with open(args.atlas) as f:
        a = json.load(f)

    G = a["grid"]
    K = a["n_kernels"]
    R = a["n_rings"]
    n_z = a["n_z"]
    n_out = a["n_out"]
    n = G * G
    stride = 4 + K * 4 + R * 3 + 5

    cells = [0.0] * (n * stride)
    for i in range(n):
        b = i * stride
        cells[b + 0] = a["well"][i]
        cells[b + 1] = a["level"][i]
        cells[b + 2] = a["mu"][i]
        cells[b + 3] = a["valid"][i]
        for k in range(K):
            o = b + 4 + k * 4
            ik = i * K + k
            cells[o + 0] = a["cx"][ik]
            cells[o + 1] = a["cy"][ik]
            cells[o + 2] = a["sigma"][ik]
            cells[o + 3] = a["w"][ik]
        for j in range(R):
            o = b + 4 + K * 4 + j * 3
            ij = i * R + j
            cells[o + 0] = a["r_rad"][ij]
            cells[o + 1] = a["r_sig"][ij]
            cells[o + 2] = a["r_amp"][ij]
        wbase = b + 4 + K * 4 + R * 3
        cells[wbase + 0] = a["wdx"][i]
        cells[wbase + 1] = a["wdy"][i]
        cells[wbase + 2] = a["wmax"][i]
        # Seed = first point of the resting cycle (curve layer z=0, point 0).
        co = (i * n_z + 0) * n_out * 2
        cells[wbase + 3] = a["curve"][co + 0]
        cells[wbase + 4] = a["curve"][co + 1]

    with open(args.out, "w") as fh:
        fh.write("// AUTO-GENERATED by gen_atlas.py — do not edit.\n")
        fh.write("// Baked phase-fold limit-cycle atlas (CPU-built, GPU-uploaded as PF_CELLS).\n")
        fh.write("#pragma once\n\n")
        fh.write("namespace phase_fold {\n\n")
        fh.write(f"static const int   PF_GRID    = {G};\n")
        fh.write(f"static const int   PF_KERNELS = {K};\n")
        fh.write(f"static const int   PF_RINGS   = {R};\n")
        fh.write(f"static const int   PF_STRIDE  = {stride};\n")
        fh.write(f"static const int   PF_NOUT    = {n_out};\n\n")
        emit_float_array(fh, "PF_E_CENTERS", a["e_centers"])
        emit_float_array(fh, "PF_L_CENTERS", a["l_centers"])
        emit_float_array(fh, "PF_VALID", a["valid"])
        emit_float_array(fh, "PF_CELLS", cells)
        # Resting cycles (z=0): GxG cells × n_out points × (x,y), row-major.
        # Used to seed the parallel limit-cycle tracer (one short arc per point).
        emit_float_array(fh, "PF_CURVE", a["curve"])
        fh.write("} // namespace phase_fold\n")

    print(f"wrote {args.out}: grid={G} K={K} R={R} stride={stride} cells={n} "
          f"({len(cells)} floats, {len(cells)*4} bytes)")


if __name__ == "__main__":
    main()
